# Change these first
owner: Frozensoft-Software # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees: # Users to assign downtime issues (optional)
  - Eiromplays

sites:
  - name: Website
    url: https://frozensoft-software-website.pages.dev
  - name: API
    url: $API_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.frozensoftsoftware.com
  logoUrl: https://imgur.com/rivb5ii.png
  name: Frozensoft Software Status
  theme: night
  introTitle: "Stay Informed with Frozensoft Software's Service Status Page"
  introMessage: At Frozensoft Software, we strive to provide our customers with the best possible service. To keep you informed, we've created this service status page powered by Upptime. Here you'll find real-time updates on the status of our services, so you can stay informed and know exactly what's going on. Check back often to stay up-to-date and as always, don't hesitate to reach out to us if you have any questions or concerns.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
